spring.application.name=develop
server.port=8080

# ===============================================
# MONGO DB CONFIGURATION
# ===============================================
spring.data.mongodb.uri=mongodb+srv://root:root@jef.dnbmzkf.mongodb.net/jeff-db?retryWrites=true&w=majority

app.jwt.issuer=develop
app.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_64_CHARS_MIN____________________
app.jwt.accessTokenMinutes=60

server.error.include-stacktrace=never